{
 "title": "Live-Streaming System Performance",
 "time": { "from": "2025-05-08T07:45:09.328Z", "to": "2025-05-08T07:46:19.055Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Used vs Free",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, \r\n       memory_used::float AS used, \r\n       memory_free::float AS free \r\nFROM \"system_Performance\" \r\nORDER BY time DESC \r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Memory Usage Over Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, memory_usage::float \r\nFROM \"system_Performance\" \r\nORDER BY time DESC \r\nLIMIT 100\r\n"
    }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT time, cpu_usage::float \r\nFROM \"system_Performance\" \r\nORDER BY time DESC \r\nLIMIT 100\r\n"
    }
   ]
  },
  {
   "title": "Disk Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time, disk_usage::float \r\nFROM \"system_Performance\" \r\nORDER BY time DESC \r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Network Traffic (Bytes Sent/Received)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, \r\n       bytes_sent::float, \r\n       bytes_received::float \r\nFROM \"system_Performance\" \r\nORDER BY time DESC \r\nLIMIT 100\r\n"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, \r\n       cpu_interrupts::int, \r\n       cpu_calls::int \r\nFROM \"system_Performance\" \r\nORDER BY time DESC \r\nLIMIT 100\r\n"
    }
   ]
  }
 ]
}